name: fitur_setting_akun
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../../common
  dependencies:
    path: ../../dependencies
  # path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.0
